services:
  demo-container-db:
    image: postgres
    mem_limit: 1536MB
    mem_reservation: 1G
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tempus-backend
    ports:
    - "5442:5432"
    volumes:
    - db-data:/var/lib/postgresql/data1
 
volumes:
  db-data: